### ISSUE TITLE
Regarding your "Wiring the Olimex board" paragraph in the documentation

### ISSUE THREAD

**Issue by kfricke** [hamishcunningham/fishy-wifi#1]
This is not really an issue, but might be changed to reflect facts of the mentioned board and not suggest useless wirings on a proto board?!

IMHO the following points are obsolete with the used Olimex board. I will comment why and reference their [board schematics](https://www.olimex.com/Products/IoT/MOD-WIFI-ESP8266-DEV/resources/MOD-WIFI-ESP8266-DEV_schematic.pdf)...

> - need gpio 15 low and cp_en high
- GPIO15 is to be found on pad 19 of the MOD-WIFI-ESP8266-DEV, which by the schematic is already pulled to GND by the default solder bridge (called MTDO on the board). So no special wiring for this is needed.
- CHIP_EN is also pulled up to 3.3V using a 12k resistor already. Noting this is nice, but also no wiring needed for this to be pulled high.

> - to flash hold gpio0 low -- sometimes I think it doesn't float high so might try using 4.7k resistor to connect it to high?

GPIO0 on pin 21 of the devboard is also pulled up by a solder bridge, but [seems to be able to be pulled down to GND](https://www.olimex.com/forum/index.php?topic=4029.msg17175#msg17175) by simply connecting pad 21 to GND (as you did). Reading the schematic shows it is pulled high over an 2K resistor already.

> - to get normal mode after flashing perhaps most useful

Should be accomplished by letting pad 21 off from GND again. Maybe add it to your DIP switch row as well!?

**Comment by hamishcunningham** [comment]
"useless wirings" -- hmmm... I guess that has been lost in translation, as I'm certainly using these wirings :-)

how about going off and hijacking another thread somewhere unrelated to you problem like the one I originally responded too?

have a more realistic one,

h
