### ISSUE TITLE
Error building nodemcu with your fishy-wifi Makefile

### ISSUE THREAD

**Issue by s137** [hamishcunningham/fishy-wifi#3]
I fully cloned your Github repository onto my local computer and tried building NodeMCU with "make nodemcu-with-dns".

This is the error I received:

---

make nodemcu-with-dns
cd /root/esp8266-stuff/nodemcu-firmware; PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/root/esp8266-stuff/esp-open-sdk-compiler/xtensa-lx106-elf/bin make UNIVERSAL_TARGET_DEFINES=-DUSE_DNS
make[1]: Betrete Verzeichnis '/root/esp8266-stuff/nodemcu-firmware'
make[2]: Betrete Verzeichnis '/root/esp8266-stuff/nodemcu-firmware/app'
make[3]: Betrete Verzeichnis '/root/esp8266-stuff/nodemcu-firmware/app/user'
DEPEND: xtensa-lx106-elf-gcc -M -Os -Os -ffunction-sections -fno-jump-tables -fdata-sections -g -O2 -Wpointer-arith -Wundef -Werror -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals -DUSE_DNS -D__ets__ -DICACHE_FLASH -DLWIP_OPEN_SRC -DPBUF_RSV_FOR_WLAN -DEBUF_LWIP -I include -I ./ -I ../../include/ets -I ../libc -I ../platform -I ../lua -I ../wofs -I ../include -I ./ -I ../../include -I ../../include/eagle user_main.c
/root/esp8266-stuff/esp-open-sdk-compiler/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc: 1: ELF: not found
/root/esp8266-stuff/esp-open-sdk-compiler/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc: 2: @@@@@@00pp@p@@@,�
                                      ,�
                                        : not found
/root/esp8266-stuff/esp-open-sdk-compiler/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc: 3: Syntax error: word unexpected (expecting ")")
xtensa-lx106-elf-gcc -Os -Os -ffunction-sections -fno-jump-tables -fdata-sections -g -O2 -Wpointer-arith -Wundef -Werror -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals -DUSE_DNS -D__ets__ -DICACHE_FLASH -DLWIP_OPEN_SRC -DPBUF_RSV_FOR_WLAN -DEBUF_LWIP   -I include -I ./ -I ../../include/ets -I ../libc -I ../platform -I ../lua -I ../wofs -I ../include -I ./ -I ../../include -I ../../include/eagle  -o .output/eagle/debug/obj/user_main.o -c user_main.c
/root/esp8266-stuff/esp-open-sdk-compiler/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc: 1: ELF: not found
/root/esp8266-stuff/esp-open-sdk-compiler/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc: 2: @@@@@@00pp@p@@@,�
                                      ,�
                                        : not found
/root/esp8266-stuff/esp-open-sdk-compiler/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc: 3: Syntax error: word unexpected (expecting ")")
make[3]: **\* [.output/eagle/debug/obj/user_main.o] Fehler 2
make[3]: Verlasse Verzeichnis '/root/esp8266-stuff/nodemcu-firmware/app/user'
make[2]: **\* [.subdirs] Fehler 2
make[2]: Verlasse Verzeichnis '/root/esp8266-stuff/nodemcu-firmware/app'
make[1]: **\* [.subdirs] Fehler 2
make[1]: Verlasse Verzeichnis '/root/esp8266-stuff/nodemcu-firmware'
make: **\* [nodemcu-with-dns] Fehler 2

---

I asumed that maybe my xtensa binarys were somehow corrupt. But exchanging them didn't resolve the error. 

I hope you can help me out.

**Comment by hamishcunningham** [comment]
hi

does "/root/esp8266-stuff/nodemcu-firmware" exist? and presumably it contains a fresh nodemcu clone?

if so I guess that maybe the nodemcu codebase has changed and broken the "compile with dns" target. in any case that target just calls the nodemcu Makefile with some params set to trigger inclusion of the DNS code -- so a next thing to try might be to copy that call and try it directly inside the nodemcu tree?

I notice you're running as root -- perhaps some paths are different between your login environment and the root environment?

if none of this helps I'd recommend the nodemcu forum on esp8266.com

hth, best

h
